[package]
name = "tests_parse_json"
version = "0.1.0"
authors = ["nuenook <nook.ittipon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = "1.0"

serde_json = "1.0"

serde_derive = "1.0"