[package]
name = "http_json_enum_cli"
version = "0.1.0"
authors = ["nuenook <nook.ittipon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
